version: '3.4'

networks:
  dotnet5crudnetwork:

services:
  dotnet5cruddb:
    container_name: dot-net5-crud-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8080:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=clover@123
    networks:
      - dotnet5crudnetwork
  dotnet5crud:
    container_name: dot-net5-crud
    image: ${DOCKER_REGISTRY-}dotnet5crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8087:80
    depends_on:
      - dotnet5cruddb
    environment:
      - DB_HOST=dotnet5cruddb
      - DB_NAME=CompanyDB
      - DB_SA_PASSWORD=clover@123
    networks:
      - dotnet5crudnetwork
